### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by Megabyte918** [Agarian/Agario-minions#1]
Hello Agarian, I was wondering if there is any way that I could add firefox support to this? Ive looked up some online tutorials, but all the ones ive seen are either outdated, or they don't work. I know this is a chrome-only extension and all, but firefox seems to run agario with extensions MUCH faster that chrome does (chrome is extremely laggy with extensions). I get a solid 60 fps on agario with firefox so I thought that if I use this on firefox then it would be much faster. Is there any way that I could edit the manifest in a way that firefox would recognize it as one of their extensions? I figured I would ask you cause you seem to know ALOT more about extensions than I do haha

**Comment by Agarian** [comment]
unfortunately, since agario powerups went down, the updated versions (both chrome and firefox) no longer work as it ran directly from the site its self. so i had no choice but to derive the code from freeagarbots.tk and i never had this extension for firefox sorry...

**Comment by Megabyte918** [comment]
Ahh I see. Guess ill just have to wait until Mozilla releases WebExtensions in a few months. But anyway, thanks for taking the time to respond and have a great night ^-^
